### ISSUE TITLE
Fix build with Qt 5.15

### ISSUE THREAD

**Issue by nicolamori** [gyunaev/birdtray#381]
**OS**: Archlinux
**Birdtray version**: 1.8.1
**Thunderbird version**: 68.9.0
**Birdtray origin**: AUR package (from source)
**Qt version**: 5.15.0 

**Description**

Compilation fails with:
```
/home/mori/builds/makepkg/birdtray/src/birdtray-1.8.1/src/trayicon.cpp: In member function ‘void TrayIcon::updateIcon()’:
/home/mori/builds/makepkg/birdtray/src/birdtray-1.8.1/src/trayicon.cpp:263:22: error: aggregate ‘QPainterPath textPath’ has incomplete type and cannot be defined
  263 |         QPainterPath textPath;
      |                      ^~~~~~~~
```

**Comment by gyunaev** [comment]
Already fixed in current source.

Please always try with the latest source before reporting the bug.
