### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by gyunaev** [gyunaev/birdtray#198]
@Abestanis: in AutoUpdater::parseDownloadUrl() we have the following code:

```
    for (auto assetInfo : assets) {
        QString name = assetInfo["name"].toString();    
```

This doesn't compile:
```
autoupdater.cpp
C:\Users\test\Builds\src\autoupdater.cpp(165): error C2676: binary '[': 'QJsonValue' does not define this operator or a conversion to a type acceptable to the predefined operator
C:\Users\test\Builds\src\autoupdater.cpp(165): error C2228: left of '.toString' must have class/struct/union
C:\Users\test\Builds\src\autoupdater.cpp(167): error C2676: binary '[': 'QJsonValue' does not define this operator or a conversion to a type acceptable to the predefined operator
C:\Users\test\Builds\src\autoupdater.cpp(167): error C2228: left of '.toString' must have class/struct/union
C:\Users\test\Builds\src\autoupdater.cpp(169): error C2676: binary '[': 'QJsonValue' does not define this operator or a conversion to a type acceptable to the predefined operator
C:\Users\test\Builds\src\autoupdater.cpp(169): error C2228: left of '.toVariant' must have class/struct/union
C:\Users\test\Builds\src\autoupdater.cpp(169): error C2228: left of '.toULongLong' must have class/struct/union
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~1.0\VC\bin\cl.exe' : return code '0x2'

```

Assets is QJsonArray, and thus assetInfo is QJsonValue. It doesn't have bracket method. Isn't it supposed to be assetInfo.toObject()["name"] ?

**Comment by Abestanis** [comment]
Please use the latest version of Qt when compiling for Windows. The bracket method [was added in Qt 5.10](https://doc.qt.io/qt-5/qjsonvalue.html#operator-5b-5d). Windows is different than Linux in that we provide the Qt shared libraries with the installer, so there is really no good reason not to use the latest Qt version. This is also why we only test the to compile for the latest Qt version for Windows on Travis.

**Comment by gyunaev** [comment]
We must support Qt version 5.6 and above. Please make sure the code builds with 5.6, and please avoid using any methods added thereafter :)

**Comment by Abestanis** [comment]
Is there a reason why we must support such an old version?

**Comment by Abestanis** [comment]
I understand it makes sense for Linux because we don't deliver Qt for Linux. But we do so for Windows so we control the Qt version we are using.

**Comment by gyunaev** [comment]
- Because some people might build it on Windows too. 
- Because there is no need to use the latest version just for the sake of using the latest version. It is justifiable if this version presents features which are critical for the application, or which would require rewriting a lot of code. When this is not the case - as it is here - I'd prefer to keep backward compatibility as much as possible.

**Comment by Abestanis** [comment]
We know that there is nobody that relies on compiling Birdtray with an old Qt version on Windows right now, because it has never worked.
Using an old version has no benefits, but there is always the risk of those old versions having unpatched security bugs. Using newer versions allows for newer features to be used, which allows for cleaner code.

I believe you are looking at this as a Linux developer. This is not really necessary on Windows.

**Comment by Abestanis** [comment]
To explain what I meant with the last sentence:
It is for example not necessary to maintain backwards compatibility, because we control the installed Qt version on Windows.

**Comment by gyunaev** [comment]
Could you please fix this? I prefer the user to have an option to use apps with old version. It should be up to them whether they want to update, but I don't want to force them.

Again, my position is that use of new functionality (this applies both to Qt > 5.6 and C++ > 14) is only acceptable when this functionality is critical for the application to work AND would otherwise require you to implement a significant chunk of code which is already implemented in the new version. Here we seem to avoid just one call to `toObject()`, hardly worth it.

**Comment by gyunaev** [comment]
> To explain what I meant with the last sentence:
> It is for example not necessary to maintain backwards compatibility, because we control the installed Qt version on Windows.

We are providing the source code, so there will be people building it from source. I don't see anyone using a provided builds in any serious enterprise, for example.

**Comment by Abestanis** [comment]
I will fix this, but could you please verify that these are the only changes that need to be made to gain backwards compatibility. I don't have any old Qt versions installed on my system, so I am unable to test this.

**Comment by gyunaev** [comment]
So far this is the only code which doesn't compile. The rest of the code is built on Linux Qt 5.6 so should be fine. My Windows build machine is based on 5.9 though.

**Comment by Abestanis** [comment]
When you compile Birdtray for the installer, please use the latest Qt version.

**Comment by gyunaev** [comment]
> When you compile Birdtray for the installer, please use the latest Qt version.

My build machine only has 5.9 which I use for all my builds. If you want to compile with the latest, you can compile it yourself :)

**Comment by Abestanis** [comment]
I don't want this to become an argument, but I do have concerns about supporting these old versions of Qt, especially because we now rely on their TSL implementation when checking for update information. If I read [this page](https://wiki.qt.io/Branch_Guidelines) correctly (and it is very possible that I didn't), only the LTS releases, the current release and the one before that will get security fixes.

> My build machine only has 5.9 which I use for all my builds.

At least you are using an LTS. :)

**Comment by gyunaev** [comment]
No need to argue. I'm ok if you want to build a release using whatever Qt version you want, even compiled from source. As long as anyone can compile the source using the stated supported versions :)

So if you'd like to go ahead and build an install yourself (and use a clean VM install to test it to make sure the dependencies are ok) - feel free to.

**Comment by Abestanis** [comment]
I'm fine if you build it using Qt 5.9, as it is a long term support version of Qt, so it will have all security fixes.

But don't you think we should not support versions of Qt that no longer receive security updates? I do understand that it is important for Linux users to be able to use Birdtray with older Qt versions, because some distros don't offer newer Qt version trough their package management system. But if those versions might contain critical security bugs, don't you think we should no longer support them? Or at least remove support for the really old ones?

**Comment by Abestanis** [comment]
On a side note, unfortunately you will need to wait for the commit that changes the Birdtray version, before you create the Windows installer. Otherwise, the `About` text will contain the wrong version. I'm waiting to hear back from @ThanosApostolou before I create that commit.

**Comment by gyunaev** [comment]
> But don't you think we should not support versions of Qt that no longer receive security updates?

Absolutely. There are still around 5% of the userbase using Windows XP. Security is only one of the variables here - and even then you'd probably be pressed to decide whether its better to use a computer with known vulnerabilities in libraries, or use no computer at all.

**Comment by Abestanis** [comment]
> There are still around 5% of the userbase using Windows XP

Seriously? 5% of all Birdtray users? How do you know that?
Also, I don't think that matters to us, because we are providing the Qt version on Windows.

I guess I'm fine with supporting older Qt versions, as long as we use a version that still actively receives security fixes when we compile Birdtray for the Windows installer. Because that is what any inexperienced Windows user will be using, so we don't want to give tham an outdated and potentially insecure Qt version.

**Comment by gyunaev** [comment]
> Seriously? 5% of all Birdtray users?

No, 5% of the overall Windows userbase. Read somewhere in news. True, its mostly non-desktop machines (such as POS which you cannot upgrade), but still.

Sure, you can build with the latest Qt if you want.

**Comment by Abestanis** [comment]
Ok, I will set up a Vm for that. I will also work on migrating from Travis to Github Actions, so we can automate the creation of the installer with the latest Qt version.
