### ISSUE TITLE
autoupdater.cpp:51:38: error: ‘class QNetworkReply’ has no member named ‘sslConfiguration’

### ISSUE THREAD

**Issue by asarubbo** [gyunaev/birdtray#627]
Hello,

this is a forward of a downstream bug opened in the Gentoo Linux bugzilla.

It looks like birdtray, at least at commit f66ead17737c6bbe139dc20717eb097965ff2994 fails to compile with the newer gcc-15.1.0 with the error: `autoupdater.cpp:51:38: error: ‘class QNetworkReply’ has no member named ‘sslConfiguration’`

The downstream report is at: https://bugs.gentoo.org/956663
The full build log is at: https://956663.bugs.gentoo.org/attachment.cgi?id=929632

Additional info about the new gcc version:
https://gcc.gnu.org/gcc-15/changes.html
https://gcc.gnu.org/gcc-15/porting_to.html

If you need more info or I can help further, please let me know.

Thanks
