### ISSUE TITLE
it looks like birdtray is not working with ubuntu-20.04

### ISSUE THREAD

**Issue by Pavanyogi121** [gyunaev/birdtray#536]
**OS**: ubuntu-20.04
**Linux Desktop Manager**: Gnome
**Birdtray version**: latest birdtray compiled from source on master branch
**Thunderbird version**: 102.4.2
**Birdtray origin**: from source
**Qt version**: qt5 

**Description**
u-20:~$ birdtray
QSystemTrayIcon::setVisible: No Icon set
QDBusTrayIcon encountered a D-Bus error: QDBusError("org.gnome.gjs.JSError.ValueError", "domain.replaceAll is not a function")

Birdtray is not laucning. There is appearing no UI of birdtray. 

**Expected behavior**

The UI should appear and count tray icon etc features should work as expected. Actually count tray icon stopped working then i tried to re-install it but it turns out that the birdtray ui itself is not loading. 

**To Reproduce**

1. On ubuntu-20.04 the birdtray ui, counter etc not working
![Screenshot from 2023-01-18 16-18-37](https://user-images.githubusercontent.com/101347903/213153995-65906cde-d002-49f1-989f-c77879c892a7.png)
 
2. 

**Screenshots**

**Additional context**

**Comment by Pavanyogi121** [comment]
It looks like I managed to get it working. The birdtray UI is also displaying correctly. I will try to add more detailed steps here later for helping others.

**Comment by rafikiphoto** [comment]
> It looks like I managed to get it working. The birdtray UI is also displaying correctly. I will try to add more detailed steps here later for helping others.

Please post your solution. It's really needed here.

**Comment by pavanyogi** [comment]
Here are the steps:
I removed the old birdtray using the following command:
```bash
sudo apt-get purge --auto-remove birdtray
```
then installed the latest birdtray (compiled from source).
```bash
sudo apt-get install qt5-default libqt5x11extras5-dev qttools5-dev libqt5svg5-dev libx11-xcb-dev -y
cd /tmp
git clone git@github.com:gyunaev/birdtray.git
cd birdtray/
ls
mkdir build
cd build
ls
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ..
sudo cmake --build . --target install
sudo updatedb
which birdtray
```
locate the Birdtray .desktop file
```bash
locate .desktop | grep Bird
```
the above command will output following, copy that file to startup folder
```bash
/usr/share/applications/com.ulduzsoft.Birdtray.desktop
sudo cp -v /usr/share/applications/com.ulduzsoft.Birdtray.desktop ~/.config/autostart
```
As of now,
```bash
u-20:~/.../autostart$ cat thunderbird.desktop
[Desktop Entry]
Type=Application
Exec=thunderbird
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_IN]=thunderbird
Name=thunderbird
Comment[en_IN]=thunderbird
Comment=thunderbird
u-20:~/.../autostart$ cat com.ulduzsoft.Birdtray.desktop 
[Desktop Entry]
Name=Birdtray
Keywords=Email;E-mail;Newsgroup;Feed;RSS
Keywords[ast]=Corréu;Corréu-e;Noticies;Discusiones;Mensaxes;Canales;RSS
Keywords[ca]=Correu;Email;E-mail;Mailing;Llistes;Notícies;RSS
Keywords[cs]=Email;E-mail;Pošta;Elektronická pošta;Diskusní skupiny;Čtečka;RSS
Keywords[da]=Email;E-mail;Epost;E-post;E-brev;Newsgroup;Nyhedsgruppe;Nyhedskilde;Usenet;Feed;RSS
Keywords[de]=Mail;E-Mail;Newsgroup;Nachrichten;Feed;RSS;Post;News;Usenet;online;lesen;schreiben
Keywords[el]=Email;E-mail;Newsgroup;Feed;RSS;ημαιλ;Αλληλογραφία;Ροή;ΡΣΣ;Συζητήσεις;Γράμματα
Keywords[es]=Email;Correo electrónico;Noticias;Discusiones;Mensajes;Canales;RSS
Keywords[fi]=Mail;E-Mail;Email;Newsgroup;Feed;RSS;posti;sähköposti;maili;meili;Usenet;uutisryhmät;syöte
Keywords[fr]=Mails;Mels;E-Mails;Emails;Courriels;Courriers;Newsgroup;Feed;RSS;Poster;Thunderbird;Lire;Écrire
Keywords[he]=דוא"ל;דוא״ל;מייל;אי-מייל;אימייל;הודעות;מוזילה;תאנדרבירד;ת׳אנדרבירד;ת'אנדרבירד;ת׳אנדרברד;ת'אנדרברד;דואל;
Keywords[hr]=email;e-mail;e-pošta;pošta;RSS
Keywords[hu]=Email;E-mail;Levél;Levelezés;Hírcsoport;Feed;Hírforrás;RSS
Keywords[it]=Email;Mail;Posta;Newsgroup;Feed;RSS
Keywords[is]=tölvupóstur;rafpóstur;fréttir;fréttahópar;samtöl;skilaboð;fréttastraumar;RSS
Keywords[ja]=Eメール;イーメール;mail;e-mail;email;メール;電子メール;ニュースグループ;ネットニュース;RSS;フィードリーダー;書く;読む;Mozilla
Keywords[nl]=Email;E-mail;Newsgroup;Feed;RSS;Nieuwsgroep;Post
Keywords[ru]=Email;E-mail;Newsgroup;Feed;RSS;почта;письма;новости;фиды
Keywords[sk]=Email;E-mail;Elektronická pošta;Diskusné skupiny;Čítačka kanálov;RSS
Keywords[uk]=Email;E-mail;Newsgroup;Feed;RSS;пошта;новини;подачі;стрічка
Keywords[vi]=Mail;E-Mail;Email;Newsgroup;Feed;RSS;Thư điện tử;Gửi thư
Keywords[zh_CN]=Mail;E-Mail;Email;Newsgroup;Feed;RSS;电子;邮件;新闻;Thunderbird;tb;雷鸟;电邮;邮箱;阅读器;
Exec=birdtray
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=com.ulduzsoft.Birdtray
Categories=Network;Email;
StartupNotify=true

u-20:~/.../autostart$
```
install [this](https://extensions.gnome.org/extension/615/appindicator-support/) gnome shell extension as described here https://askubuntu.com/questions/1438275/system-tray-icons-all-disappeared/1439838#1439838

and replace one line code in the file ~/.local/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js 
from 
```bash
Logger._domain = domain.replaceAll(' ', '-');
```
to 
```bash
Logger._domain = domain.replaceAll ? domain.replaceAll(' ', '-')
    : domain.split(' ').join('-');
```
then restart the system. After that birdtray will display unread count icon etc as expected. To get the birdtray UI, click on settings when birdtray is displaying the unread count icon. The birdtray UI will not be accessible directly. The birdtray UI will be accessible from unread icon only. 
some helpful links:
https://www.reddit.com/r/Thunderbird/comments/vr7h4n/comment/j3u934i/?utm_source=share&utm_medium=web2x&context=3
some screenshots are attached for reference:


![Screenshot from 2023-01-21 13-36-41](https://user-images.githubusercontent.com/13834016/213857886-736a4ffe-3521-4b69-8a81-8642556e5fbe.png)
![Screenshot from 2023-01-21 12-59-51](https://user-images.githubusercontent.com/13834016/213857900-156b313f-e622-4272-8d7c-ce9d58aebeb8.png)
