### ISSUE TITLE
Include path not found

### ISSUE THREAD

**Issue by yjfguhd** [gyunaev/birdtray#319]
I don't know why, but to build 1.8.0, I had to edit a few files and hard code the path to `ui_*.h` files, because I was getting failures like this:

```
[ 32%] Building CXX object CMakeFiles/birdtray_lib.dir/src/updatedownloaddialog.cpp.o
/home/user/src/birdtray/src/mailaccountdialog.cpp:8:34: fatal error: ui_mailaccountdialog.h: No such file or directory
compilation terminated.
```

Once I updated the `#include` lines to point to `/home/user/src/birdtray/build/ui_mailaccountdialog.h`, in this example, it built fine. I suspect this is an issue with my environment, but I was merely following the README.md instructions:

```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
```

I don't recall having to do this for 1.7.0.

**Comment by Abestanis** [comment]
Which version of Cmake are you using and on which Os are you compiling?

**Comment by yjfguhd** [comment]
cmake 3.5.2, Linux 64-bit (Slackware 14.2).

**Comment by Abestanis** [comment]
Did you use a fresh clone of the repository or did you pull into a previously cloned repository? If the latter, did you compile Birdtray before you pulled the 1.8.0 changes?

**Comment by yjfguhd** [comment]
It wasn't a fresh clone. I pulled, checked out the 1.8.0 tag, `git checkout -- .`'d and `git clean -df`'d, then built.

I've now just done a fresh clone, checked out the tag, and had the same issues when building. In fact, I had this issue when I downloaded the tarball from the releases page, and built that separately.

**Comment by Abestanis** [comment]
Interesting, I can reproduce this on an Ubuntu machine using `cmake 3.5.2`, but it compiles on the same machine using `cmake 3.10.2`. I will have a look if we can do something here, but we might just be able to raise the minimum supported cmake version. Are you able to update your cmake?

**Comment by Abestanis** [comment]
Ok, found the reason:
Between 1.7.0 and 1.8.0, the line [`set(CMAKE_INCLUDE_CURRENT_DIR ON)`](https://github.com/gyunaev/birdtray/blob/RELEASE_1.7.0/CMakeLists.txt#L54) ([cmake documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_INCLUDE_CURRENT_DIR.html)) was removed from the cmake file. It was not necessary for newer cmake versions, because they no longer put the generated header files in `CMAKE_CURRENT_BINARY_DIR`.

We will have to put that line back. You should be able to edit the `CMakeLists.txt` yourself locally and then compile Birdtray.

**Comment by yjfguhd** [comment]
Confirmed it builds with that change — thank you, and good spot. I'm glad it was such a simple fix.
