### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by undeference** [gyunaev/birdtray#159]
**OS**: Fedora release 30 (Thirty)
**Birdtray version**: git upstream
**Thunderbird version**: 68.1.1
**Birdtray origin**: git
**Qt version**: 5.12.5

**Description**
Compilation failure for days using upstream git code

**Expected behavior**
Compiles successfully

**To Reproduce**

1. (cd src && qmake-qt5 && make)
2. 

**Screenshots**

**Additional context**
Initially, I got `error: ‘QCoreApplication’ has not been declared` but then it changed to
```
WARNING: Failure to find: debug/dynamic_de.qm
WARNING: Failure to find: debug/dynamic_en.qm
WARNING: Failure to find: debug/main_de.qm
WARNING: Failure to find: debug/main_en.qm
make: *** No rule to make target 'debug/dynamic_de.qm', needed by 'debug/translations/dynamic_de.qm'.  Stop.
```
git bisect tells me
```
The first bad commit could be any of:
42c5008eb04d9e2754ad1332b03ec2dc2fd8d21d
b0f2f96b5b8f9830de5801c19e39c06319b531c6
bc8ca2592d817f25c2eec9560e7e2bce58f62ec4
c112e6bcb2ab2a247e3eb3c19f7d0974625c5fda
36d0f93dc110ca636e920879a4683409135868a3
6068062884b39629832ba563e4fbf1c5e6ef24e2
1961c3b4615f1c5d1082d86e0881349a62c85555
We cannot bisect more!
```

**Comment by Abestanis** [comment]
Looks like support for `CONFIG += lrelease` was [only introduced a year ago](https://github.com/qt/qtbase/commit/01d2f35b6988edacc741b358703d16d4cd8c199a) for Qt 5.12, but the qmake version on Ubuntu was compiled using Qt 5.9.5.

Travis didn't catch this, because it uses cmake as the build system, which is unaffected by this bug.
The immediate workaround is to use cmake or to comment out the `COPIES += translations` [here](https://github.com/gyunaev/birdtray/blob/master/src/birdtray.pro#L103) with a `#`.

I did test the qmake compile on Windows, but the Qt installer on Windows includes an up to date qmake.
To prevent something like this in the future, we could
a) add qmake compilation to Travis.
b) remove support for qmake and move to cmake.
I'm personally in favour of b), what's your opinion, @gyunaev?

**Comment by gyunaev** [comment]
We can remove qmake support.
